import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"..");
const lesson=readFileSync(resolve(root,"learning-paths/systems-engineering/05-latency-distribution-sampling-performance-budget.md"),"utf8");
for(const type of ["overview","concept","example","reproduce","modify","troubleshoot","project","career"]) assert.match(lesson,new RegExp(`data-context-type="${type}"`),`missing ${type}`);
for(const phrase of ["p50_us=30","p95_us=120","p99_us=200","elapsed=observed-not-asserted"]) assert.ok(lesson.includes(phrase),`missing ${phrase}`);
assert.ok(lesson.includes("零基础兴趣")&&lesson.includes("有基础求职"),"four profiles missing");
const project=resolve(root,"site-src/examples/systems-engineering/diagnostic-service-v05");
const tests=spawnSync(resolve(root,".venv/bin/python"),["-m","unittest","-v","test_performance_budget.py"],{cwd:project,encoding:"utf8"});
assert.equal(tests.status,0,tests.stdout+tests.stderr);assert.match(tests.stdout+tests.stderr,/Ran 5 tests/);
console.log(JSON.stringify({valid:true,lesson_id:"systems-engineering-05",project:"diagnostic-service-v05",tests:5,percentile_method:"nearest-rank",real_clock_observational:true,fixed_timing_assertion:false,four_profiles_addressed:true},null,2));
