#!/usr/bin/env node
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
const root=resolve(import.meta.dirname,"..");const python=join(root,".venv/bin/python");const pyProject=join(root,"exercises/cs-core/traceable-graph-traversal-lab/python");const cppProject=join(root,"exercises/cs-core/traceable-graph-traversal-lab/cpp");const micro=join(root,"site-src/examples/algorithm-foundation/undirected_graph_normalization_trace.py");const temp=mkdtempSync(join(tmpdir(),"be-cs-graph-"));
function run(c,a,o={}){return spawnSync(c,a,{cwd:root,encoding:"utf8",...o});}function ok(r,l){assert.equal(r.status,0,`${l}\n${r.stdout}\n${r.stderr}`);}
try{const sample=run(python,[micro]);ok(sample,"无向图规范化轨迹失败");assert.match(sample.stdout,/canonical=\[\(0, 2\), \(1, 3\), \(3, 4\)\]/);assert.match(sample.stdout,/degree_sum=6 twice_edges=6/);assert.match(sample.stdout,/reverse_duplicate=rejected reason=duplicate undirected edge/);const env={...process.env,PYTHONPATH:join(pyProject,"src")};ok(run(python,["-m","unittest","discover","-s","tests","-v"],{cwd:pyProject,env}),"Python测试失败");ok(run(python,["-m","mypy","--strict","src","tests"],{cwd:pyProject,env}),"mypy失败");const build=join(temp,"cpp-build");ok(run("cmake",["-S",cppProject,"-B",build,"-DCMAKE_BUILD_TYPE=Debug"]),"C++配置失败");ok(run("cmake",["--build",build,"--config","Debug","--parallel"]),"C++构建失败");ok(run("ctest",["--test-dir",build,"--build-config","Debug","--output-on-failure"]),"CTest失败");const cpp=join(build,"traceable_graph_traversal_lab");for(const mode of ["graph","bfs","dfs"]){const p=run(python,["-m","traceable_graph_traversal_lab",mode],{cwd:pyProject,env});const c=run(cpp,[mode]);ok(p,`Python ${mode}失败`);ok(c,`C++ ${mode}失败`);assert.equal(c.stdout.trim(),p.stdout.trim());}console.log("简单无向图、邻接表示与输入边界验证通过");}finally{rmSync(temp,{recursive:true,force:true});}
