import assert from"node:assert/strict";
import{spawnSync}from"node:child_process";
import{readFileSync}from"node:fs";
import{resolve}from"node:path";
const root=resolve(import.meta.dirname,"..");
const lesson=readFileSync(resolve(root,"learning-paths/llm-agent/rag-application-engineering/02-chunking-models-strategies-comparison.md"),"utf8");
for(const type of["overview","concept","example","reproduce","modify","troubleshoot","project"])assert.match(lesson,new RegExp(`data-context-type="${type}"`));
for(const phrase of["strategies:5,models=fixed,recursive,structure,semantic,parent-child","boundary-coverage,context-precision,size-distribution,duplicate-rate","real-semantic-model:false","不能把整段 parent 都声明为支持证据","零基础兴趣","有基础求职"])assert.ok(lesson.includes(phrase),phrase);
const cwd=resolve(root,"site-src/examples/rag-application-engineering/intelligent-learning-assistant-v26");
const tests=spawnSync("python3",["-m","unittest","-v","test_chunking_lab.py"],{cwd,encoding:"utf8"});
assert.equal(tests.status,0,tests.stdout+tests.stderr);assert.match(tests.stdout+tests.stderr,/Ran 8 tests/);
const report=spawnSync("python3",["chunking_lab.py"],{cwd,encoding:"utf8"});
assert.equal(report.status,0,report.stderr);assert.match(report.stdout,/strategies:5/);
console.log(JSON.stringify({valid:true,lesson_id:"rag-application-engineering-02",tests:8,chunkers:5,real_model:false},null,2));
